name: ModernCowgirl
favicon: null
layout_spectrum: 0.6311882042791694
typography_spectrum: 0.3232247477862984
title: Modern Cowgirl
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6800592846702784
  lightness: 0.4573291838169098
  saturation: 0.6877345591783524
  rhythmicContrast: 0.8775537682231516
purpose: []
